version: '3'

services:

  vote:
    image: dockersamples/examplevotingapp_vote:before
    ports:
      - 5000:80
    networks:
      - Frontend

  redis:
    image: redis:3.2
    networks:
      - Frontend

  worker:
    image: dockersamples/examplevotingapp_worker
    networks:
      - Frontend
      - Backend

  db:
    image: postgres:9.4
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      # POSTGRES_USER: test_db_user1
      # POSTGRES_DB: test_db_1
      # POSTGRES_PASSWORD: password
    networks:
      - Backend

  result:
    image: dockersamples/examplevotingapp_result:before
    ports:
      - 5001:80
    networks:
      - Backend

networks:
  Backend:
  Frontend:
